# Generated by Django 5.2.13 on 2026-08-03 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='resume_file',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='user',
            name='video_resume_file',
            field=models.FileField(blank=True, upload_to='video_resumes/'),
        ),
    ]
