# Generated by Django 5.2.8 on 2026-08-05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_user_resume_file_user_video_resume_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicantProfileData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("personal", models.JSONField(blank=True, default=dict)),
                ("job_preferences", models.JSONField(blank=True, default=dict)),
                ("experience", models.JSONField(blank=True, default=dict)),
                ("academic", models.JSONField(blank=True, default=dict)),
                ("skills", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.OneToOneField(on_delete=models.deletion.CASCADE, related_name="profile_data", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
