# Generated by Django 5.2.13 on 2026-08-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_loginsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='video_resume_url',
            field=models.URLField(blank=True),
        ),
    ]
