# Generated by Django 5.2.13 on 2026-08-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_bank_account',
            field=models.FileField(blank=True, upload_to='internship_documents/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_bank_account_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_passport_photo',
            field=models.FileField(blank=True, upload_to='internship_documents/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_passport_photo_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_resume',
            field=models.FileField(blank=True, upload_to='internship_documents/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_resume_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_transcript',
            field=models.FileField(blank=True, upload_to='internship_documents/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_transcript_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_university_letter',
            field=models.FileField(blank=True, upload_to='internship_documents/'),
        ),
        migrations.AddField(
            model_name='candidateapplication',
            name='internship_university_letter_original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
