# Generated by Django 5.2.13 on 2026-07-31 01:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('vacancy_type', models.CharField(choices=[('job', 'Job'), ('internship', 'Internship')], max_length=20)),
                ('department', models.CharField(max_length=120)),
                ('location', models.CharField(default='Kuching, Sarawak', max_length=160)),
                ('employment_type', models.CharField(blank=True, max_length=80)),
                ('grade', models.CharField(blank=True, max_length=50)),
                ('summary', models.TextField()),
                ('responsibilities', models.TextField(blank=True)),
                ('requirements', models.TextField(blank=True)),
                ('closing_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'vacancy_type'], name='vacancy_status_type_idx'), models.Index(fields=['department'], name='vacancy_department_idx'), models.Index(fields=['closing_date'], name='vacancy_closing_idx')],
            },
        ),
    ]
