# Generated by Codex on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="official_document",
            field=models.FileField(blank=True, upload_to="vacancy_documents/"),
        ),
    ]
