# Generated by Codex on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("jobs", "0002_vacancy_official_document")]

    operations = [
        migrations.AddField(model_name="vacancy", name="advertisement_no", field=models.CharField(blank=True, max_length=60)),
        migrations.AddField(model_name="vacancy", name="service_group", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="vacancy", name="service_classification", field=models.CharField(blank=True, max_length=100)),
        migrations.AddField(model_name="vacancy", name="minimum_salary", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="vacancy", name="maximum_salary", field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
        migrations.AddField(model_name="vacancy", name="application_instructions", field=models.TextField(blank=True)),
        migrations.AddField(model_name="vacancy", name="application_notes", field=models.TextField(blank=True)),
    ]
