# Generated by Codex on 2026-08-05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("jobs", "0003_vacancy_advertisement_fields")]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="division",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
