import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { apiRequest, clearAuthSession, getStoredUser } from "../../lib/authApi";
import { Icon } from "../applicant/ApplicantAuthShared";

const menu = [
  ["dashboard", "Dashboard", "dashboard"], ["section", "PEMOHON"], ["group", "Pemohon", "applicants"], ["section", "DBKU"], ["admin_panel_settings", "Admin HRM", "admins"], ["section", "SISTEM"], ["shield_person", "SuperAdmin", "superadmins"],
];

export default function SuperAdminDashboardPage() {
  const navigate = useNavigate(); const user = getStoredUser(); const [view, setView] = useState("dashboard");
  useEffect(() => { if (!user) navigate("/login", { replace: true }); else if (user.role !== "superadmin") navigate("/profile", { replace: true }); }, [navigate, user]);
  if (!user || user.role !== "superadmin") return null;
  return <div className="fas-super-page"><aside className="fas-super-side"><div className="fas-super-brand"><img src="/logo-dbku.png" alt="DBKU" /><div><strong>Portal Kerjaya DBKU</strong><small>Career Portal</small></div><button type="button"><Icon>menu</Icon></button></div><nav>{menu.map((item) => item[0] === "section" ? <p key={item[1]}>{item[1]}</p> : <button className={view === item[2] ? "active" : ""} key={item[2]} onClick={() => setView(item[2])} type="button"><Icon>{item[0]}</Icon>{item[1]}</button>)}</nav></aside><div className="fas-super-work"><header><strong>Selamat datang, {user.full_name || "SUPER ADMIN"}</strong><div><button type="button"><Icon>language</Icon> BM</button><button className="fas-lang-active" type="button">EN</button><button type="button"><Icon>notifications</Icon></button><button type="button"><Icon>account_circle</Icon></button><button onClick={() => { clearAuthSession(); navigate("/login", { replace: true }); }} type="button"><Icon>logout</Icon></button></div></header><main>{view === "dashboard" ? <Dashboard /> : <Management view={view} />}</main></div></div>;
}

function Dashboard() { return <><h1>SuperAdmin Dashboard</h1><p className="fas-description">Pantau akses akaun dan pengurusan portal.</p><div className="fas-account-cards"><AccountCard icon="group" title="Akaun Pemohon" rows={[["Pemohon", "—"]]} /><AccountCard icon="account_balance" title="Akaun DBKU" rows={[["Admin HRM", "—"]]} /><AccountCard icon="shield_person" title="Akaun Sistem" rows={[["SuperAdmin", "1"]]} /></div><div className="fas-dashboard-bottom"><section><h2>Aktiviti Terkini</h2><p>Aktiviti akaun terkini akan dipaparkan di sini.</p><div className="fas-empty">Tiada aktiviti direkodkan.</div></section><section><h2>Ringkasan Akses</h2><p>Super Admin hanya boleh mencipta akaun dalaman HRM.</p><div className="fas-access"><Icon>verified_user</Icon> Akses Pengurusan Akaun HRM</div></section></div></> }
function AccountCard({ icon, rows, title }) { return <section className="fas-account-card"><h2><span><Icon>{icon}</Icon></span>{title}</h2>{rows.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</section> }
function Management({ view }) { const isHrm = view === "admins"; const title = isHrm ? "Pengurusan Admin DBKU" : view === "applicants" ? "Pengurusan Pemohon" : "Pengurusan SuperAdmin"; return <><div className="fas-page-heading"><div><h1>{title}</h1><p className="fas-description">{isHrm ? "Cipta akaun dalaman bagi Bahagian Pengurusan Sumber Manusia (HRM)." : "Paparan pengurusan akaun sementara."}</p></div>{isHrm ? <button className="fas-primary" type="button"><Icon>person_add</Icon> Tambah Akaun</button> : null}</div><section className="fas-filter"><input placeholder="Cari nama, emel atau nombor telefon" /><button className="fas-primary" type="button"><Icon>search</Icon> Tapis</button><button type="button">Set Semula</button></section><section className="fas-table-card"><h2>{isHrm ? "Senarai Admin HRM" : title.replace("Pengurusan ", "Senarai ")}</h2><p>Tiada rekod untuk dipaparkan.</p>{isHrm ? <HrmForm /> : <div className="fas-empty">Modul ini akan ditambah kemudian.</div>}</section></> }
function HrmForm() { const [form, setForm] = useState({ full_name:"", email:"", password:"" }); const [message,setMessage]=useState(""); const submit=async(e)=>{e.preventDefault();try{await apiRequest("/auth/internal-hrm-accounts/",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});setMessage("Akaun HRM berjaya dicipta.");setForm({full_name:"",email:"",password:""});}catch(error){setMessage(error.message)}}; return <form className="fas-hrm-form" onSubmit={submit}><label>Nama Penuh<input required value={form.full_name} onChange={e=>setForm({...form,full_name:e.target.value})} /></label><label>Emel DBKU<input required type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} /></label><label>Kata Laluan Sementara<input required minLength="8" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} /></label>{message?<p>{message}</p>:null}<button className="fas-primary" type="submit"><Icon>person_add</Icon>Cipta Akaun HRM</button></form> }
