import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { clearAuthSession, getStoredUser } from "../../lib/authApi";
import { Icon } from "../applicant/ApplicantAuthShared";

const items = [["dashboard", "Papan Pemuka"], ["section", "PEMOHON"], ["group", "Pemohon"], ["section", "DBKU"], ["admin_panel_settings", "Pentadbir"], ["section", "SISTEM"], ["shield_person", "Super Admin"]];

export default function SuperAdminShellPage() {
  const navigate = useNavigate(); const user = getStoredUser();
  const [isAccountMenuOpen, setIsAccountMenuOpen] = useState(false);
  useEffect(() => { if (!user) navigate("/login", { replace: true }); else if (user.role !== "superadmin") navigate("/", { replace: true }); }, [navigate, user]);
  if (!user || user.role !== "superadmin") return null;
  const displayName = (user.full_name || user.first_name || "Super Admin").toUpperCase();
  return <div className="min-h-screen min-w-[900px] bg-slate-50"><aside className="fixed inset-y-0 left-0 flex w-[350px] flex-col border-r border-slate-200 bg-white"><div className="grid h-[72px] grid-cols-[minmax(0,1fr)_auto] items-center gap-2 border-b border-slate-200 px-4"><div className="flex items-center gap-3"><img className="h-9 w-9 object-contain" src="/logo-dbku.png" alt="DBKU"/><div><p className="font-semibold text-slate-950">Portal Kerjaya DBKU</p><p className="text-xs text-slate-500">Super Admin</p></div></div><button className="rounded-md border border-slate-200 bg-white p-2 text-slate-700"><Icon>menu</Icon></button></div><nav className="space-y-1 px-4 py-5">{items.map(([icon, label], index) => icon === "section" ? <p className="px-4 pb-2 pt-4 text-[13px] font-bold text-slate-400" key={`${label}-${index}`}>{label}</p> : <button className={`flex w-full items-center gap-4 rounded-md px-4 py-3 text-left text-[15px] font-semibold ${index === 0 ? "bg-emerald-50 text-slate-950" : "text-slate-950"}`} key={`${label}-${index}`} type="button"><Icon>{icon}</Icon>{label}</button>)}</nav></aside><main className="ml-[350px] min-h-screen bg-slate-50"><header className="flex h-[72px] items-center justify-between border-b border-emerald-100 bg-white px-11"><div><p className="text-sm font-bold text-slate-950">Selamat datang</p><strong className="mt-1 block text-[17px] text-slate-950">{displayName}</strong></div><div className="relative flex items-center gap-4"><button className="flex h-12 w-12 items-center justify-center rounded-full border border-slate-200 bg-white text-slate-600"><Icon>notifications</Icon></button><button className="flex items-center gap-3" onClick={() => setIsAccountMenuOpen((current) => !current)} type="button"><span className="flex h-12 w-12 items-center justify-center rounded-full border border-emerald-300 bg-emerald-100 text-lg font-bold text-emerald-700">{displayName.charAt(0)}</span><Icon>expand_more</Icon></button>{isAccountMenuOpen ? <div className="absolute right-0 top-14 z-20 w-44 rounded-md border border-slate-200 bg-white p-1.5 shadow-xl"><button className="flex w-full items-center gap-3 rounded-md px-3 py-2 text-left text-sm font-semibold text-red-700 hover:bg-red-50" onClick={() => { clearAuthSession(); navigate("/login", { replace: true }); }} type="button"><Icon>logout</Icon>Log Keluar</button></div> : null}</div></header></main></div>;
}
